[package]
name = "actix-redis"
version = "0.9.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Redis integration for Actix web"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["actix", "redis", "async", "session"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-extras.git"
documentation = "https://docs.rs/actix-redis/"
categories = ["network-programming", "asynchronous"]
exclude = [".cargo/config"]
edition = "2018"

[lib]
name = "actix_redis"
path = "src/lib.rs"

[features]
default = ["web"]

# actix-web integration
web = [
    "actix-http/actors",
    "actix-service",
    "actix-web",
    "actix-session/cookie-session",
    "rand",
    "serde",
    "serde_json"
]

[dependencies]
actix = { git = "https://github.com/ddboline/actix.git", branch = "master" }

log = "0.4.14"
backoff = "0.3.0"
derive_more = "0.99.11"
futures-util = { version = "0.3.12", default-features = false }
futures-channel = { version = "0.3.12", default-features = false }
redis-async = { version = "0.8", default-features = false, features = ["tokio10"] }
actix-rt = "2.0.0"
time = "0.2.9"
tokio = "1"
tokio-util = "0.6"

# actix-session
actix-web = { version = "4.0.0-beta.1", default_features = false, optional = true }
actix-http = { version = "3.0.0-beta.1", optional = true }
actix-service = { version = "2.0.0-beta.4", optional = true }
actix-session = { path="../actix-session", optional = true }
rand = { version = "0.8", optional = true }
serde = { version = "1.0.123", optional = true }
serde_json = { version = "1.0.62", optional = true }

[dev-dependencies]
env_logger = "0.8"
serde_derive = "1.0"
